# ----------------------------------------------------------------
# BUILD STAGE - bedrock / pull image
# ----------------------------------------------------------------

FROM rabbitmq:management AS stage-base
